### ISSUE TITLE
can you supply all file 

### ISSUE THREAD

**Issue by DE45A** [shadeMe/Fuz-Ro-D-oh-64#4]
![image](https://user-images.githubusercontent.com/79677939/201583348-6661954e-5462-482a-929a-bea83b5b5697.png)
I don't know where I am doing wrong
I just fix 
```
SecondsOfSilence = WordCount / ((kWordsPerSecond > 0) ? kWordsPerSecond : 2) + 1;
```
to
```
SecondsOfSilence = WordCount / ((kWordsPerSecond > 0) ? kWordsPerSecond : 2) + 5;
```
thank you

**Comment by drfuzzyness** [comment]
From what I recall, you need to clone https://github.com/shadeMe/SME-Sundries to your computer and set an environment variable that points to where you cloned it. I believe the env is `SMESundriesIncludePath`, but double check the `.vcxproj` files for references to it.

**Comment by DE45A** [comment]
![image](https://user-images.githubusercontent.com/79677939/202076269-0243873c-207e-4981-82f3-4e6ab47e6643.png)
I have a new problem
what went wrong

**Comment by drfuzzyness** [comment]
Look for any references to the command `cscript.exe "BuildIncrement.jse"` in the Visual Studio Project and remove it from the project. It looks like it's defined in at least two places:

https://github.com/shadeMe/Fuz-Ro-D-oh-64/blob/afc5ec8e72fec8f68c63739fc653e7ea726eefb8/Fuz%20Ro%20D'oh%2064.vcxproj#L80-L82

https://github.com/shadeMe/Fuz-Ro-D-oh-64/blob/afc5ec8e72fec8f68c63739fc653e7ea726eefb8/Fuz%20Ro%20D'oh%2064.vcxproj#L119-L122

Search around for any references to those strings.

**Comment by drfuzzyness** [comment]
While you're at it, look through those `.vcxproj` files as it looks like several other environment variables that need to be set on your computer including an environment variable `Skyrim64Path`.

**Comment by shadeMe** [comment]
Closed as it's not an issue per-se.
