### ISSUE TITLE
Support for Skyrim AE 1170

### ISSUE THREAD

**Issue by mirek967** [shadeMe/Fuz-Ro-D-oh-64#8]
There is released new version of Skyrim.
Please add support for this release.

**Comment by shadeMe** [comment]
From the NexusMods page.

![image](https://github.com/shadeMe/Fuz-Ro-D-oh-64/assets/214450/3aad7669-ddc5-4265-ac7d-fdd472d06865)

**Comment by mirek967** [comment]
Thank you for your great work.
